# Application Configuration
server:
  port: 8093
  error:
    include-message: always
    
# To see H2 Console in Browser:
# http://localhost:093/h2-console
# Enabling H2 console
spring:
  h2:
    console:
      enabled: true
      
# ================================
# DB
# ================================
  datasource:
    url: jdbc:h2:mem:invoiceDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false  
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"    
